version: '3'

services:
    brevets:
        build: brevets/.
        command: python flask_brevets.py
        ports: 
            - "5001:5000"
        depends_on:
            - brevetsmongodb
        environment:
          MONGODB_HOSTNAME: brevetsmongodb
        volumes:
            - type: bind
              source: brevets/
              target: /app
    brevetsmongodb:
        image: mongo:5.0.5
